apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels: {control-plane: controller-manager}
  template:
    metadata:
      labels: {control-plane: controller-manager}
    spec:
      serviceAccountName: controller-manager
      containers:
      - name: manager
        image: controller:latest
        args: ["--leader-elect"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {drop: ["ALL"]}
          runAsNonRoot: true
        resources:
          requests: {cpu: 10m, memory: 64Mi}
          limits: {cpu: 500m, memory: 256Mi}
