apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: kick-example-008
  labels:
    touch: "1"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"example.com":{"auth":"ZmFrZTpmYWtl"}}}' 
