#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

cat > llms.txt <<'EOF'
# KICK Operator (AI quick context)

KICK watches Secret and ConfigMap changes and evaluates whether a workload restart is required and currently allowed.

## APIs
- KickRequest (`kick.corewire.io/v1alpha1`): durable restart request state machine.
- KickPolicy (`kick.corewire.io/v1alpha1`): workload scope, GitOps gate, schedule, rate limit, dry-run.
- NotificationPolicy (`kick.corewire.io/v1alpha1`): outbound webhook delivery for KickRequest outcomes.

## Runtime model
- Source observation detects relevant dependency content changes.
- KickRequest reconciliation re-resolves owner/gates and re-checks freshness before restart.
- Restart action patches `kubectl.kubernetes.io/restartedAt` on Deployment, StatefulSet and DaemonSet.
- Argo Rollouts are restarted via `spec.restartAt` instead, so the canary strategy is not re-run.

## Optional integrations
- GitOps gating is opt-in: `spec.gitOps.provider` defaults to `None`. Providers: ArgoCD, Flux, Kargo, Auto.
- `--enable-argocd` and `--enable-flux` default to true.
- `--enable-kargo`, `--enable-argo-rollouts`, and `--enable-csi-integration` default to false.

## Deliberate non-goals
- Dependencies declared by name are not supported; only proven env/volume/CSI references are used.
- KICK has no admission webhook and never holds pods `Pending`.
- OpenShift `DeploymentConfig` is not supported.

## Key references
- docs/content/docs/installation.md
- docs/content/docs/quickstart.md
- docs/content/docs/comparison.md
- docs/content/docs/guides/without-gitops.md
- docs/content/docs/reference/kickrequest.md
- docs/content/docs/reference/kickpolicy.md
- docs/content/docs/reference/notificationpolicy.md
- docs/content/docs/reference/configuration.md
- docs/content/docs/reference/metrics.md
- docs/content/docs/reference/events.md

## Security
- Controller needs read access to Secrets/ConfigMaps to evaluate freshness.
- KICK never logs Secret data or content digests.
EOF

{
  echo "# KICK Operator (AI full context)"
  echo
  echo "Generated by hack/gen-docs.sh."
  echo
  cat llms.txt
  echo

  while IFS= read -r -d '' file; do
    echo
    echo "## Source: ${file}"
    echo
    cat "${file}"
  done < <(find docs/content/docs -type f -name "*.md" -print0 | LC_ALL=C sort -z)
} > llms-full.txt

# Publish alongside the Hugo site so agents can fetch it over HTTP.
cp llms-full.txt docs/static/llms-full.txt

echo "Generated llms.txt and llms-full.txt"
