#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

cat > llms.txt <<'EOF'
# KICK Operator (AI quick context)

KICK watches Secret and ConfigMap changes and evaluates whether a Deployment restart is required and currently allowed.

## APIs
- KickRequest (`kick.corewire.io/v1alpha1`): durable restart request state machine.
- KickPolicy (`kick.corewire.io/v1alpha1`): workload scope and GitOps gate policy.

## Runtime model
- Source observation detects relevant dependency content changes.
- KickRequest reconciliation re-resolves owner/gates and re-checks freshness before restart.
- Restart action patches `kubectl.kubernetes.io/restartedAt` on Deployments only.

## Key references
- docs/getting-started/installation.md
- docs/getting-started/quickstart.md
- docs/reference/kickrequest.md
- docs/reference/kickpolicy.md
- docs/reference/configuration.md
- docs/reference/metrics.md
- docs/reference/events.md

## Security
- Controller needs read access to Secrets/ConfigMaps to evaluate freshness.
- KICK never logs Secret data or content digests.
EOF

{
  echo "# KICK Operator (AI full context)"
  echo
  echo "Generated by hack/gen-docs.sh."
  echo
  cat llms.txt
  echo

  for section in getting-started concepts guides reference operations; do
    for file in $(find "docs/${section}" -maxdepth 1 -type f -name "*.md" | sort); do
      echo
      echo "## Source: ${file}"
      echo
      cat "${file}"
    done
  done
} > llms-full.txt

echo "Generated llms.txt and llms-full.txt"
