//go:build !ignore_autogenerated

// Copyright 2026.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateStatus) DeepCopyInto(out *GateStatus) {
	*out = *in
	if in.RequeueAt != nil {
		in, out := &in.RequeueAt, &out.RequeueAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GateStatus.
func (in *GateStatus) DeepCopy() *GateStatus {
	if in == nil {
		return nil
	}
	out := new(GateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsOwnerStatus) DeepCopyInto(out *GitOpsOwnerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsOwnerStatus.
func (in *GitOpsOwnerStatus) DeepCopy() *GitOpsOwnerStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsOwnerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicy) DeepCopyInto(out *KickPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicy.
func (in *KickPolicy) DeepCopy() *KickPolicy {
	if in == nil {
		return nil
	}
	out := new(KickPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KickPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicyDiscoverySpec) DeepCopyInto(out *KickPolicyDiscoverySpec) {
	*out = *in
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicyDiscoverySpec.
func (in *KickPolicyDiscoverySpec) DeepCopy() *KickPolicyDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(KickPolicyDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicyGitOpsSpec) DeepCopyInto(out *KickPolicyGitOpsSpec) {
	*out = *in
	if in.RequireReconciled != nil {
		in, out := &in.RequireReconciled, &out.RequireReconciled
		*out = new(bool)
		**out = **in
	}
	in.Schedule.DeepCopyInto(&out.Schedule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicyGitOpsSpec.
func (in *KickPolicyGitOpsSpec) DeepCopy() *KickPolicyGitOpsSpec {
	if in == nil {
		return nil
	}
	out := new(KickPolicyGitOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicyList) DeepCopyInto(out *KickPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KickPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicyList.
func (in *KickPolicyList) DeepCopy() *KickPolicyList {
	if in == nil {
		return nil
	}
	out := new(KickPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KickPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicyScheduleSpec) DeepCopyInto(out *KickPolicyScheduleSpec) {
	*out = *in
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]KickPolicyWindow, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicyScheduleSpec.
func (in *KickPolicyScheduleSpec) DeepCopy() *KickPolicyScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(KickPolicyScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicySpec) DeepCopyInto(out *KickPolicySpec) {
	*out = *in
	in.Discovery.DeepCopyInto(&out.Discovery)
	in.GitOps.DeepCopyInto(&out.GitOps)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicySpec.
func (in *KickPolicySpec) DeepCopy() *KickPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KickPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicyStatus) DeepCopyInto(out *KickPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicyStatus.
func (in *KickPolicyStatus) DeepCopy() *KickPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(KickPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickPolicyWindow) DeepCopyInto(out *KickPolicyWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickPolicyWindow.
func (in *KickPolicyWindow) DeepCopy() *KickPolicyWindow {
	if in == nil {
		return nil
	}
	out := new(KickPolicyWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickRequest) DeepCopyInto(out *KickRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickRequest.
func (in *KickRequest) DeepCopy() *KickRequest {
	if in == nil {
		return nil
	}
	out := new(KickRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KickRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickRequestList) DeepCopyInto(out *KickRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KickRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickRequestList.
func (in *KickRequestList) DeepCopy() *KickRequestList {
	if in == nil {
		return nil
	}
	out := new(KickRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KickRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickRequestSpec) DeepCopyInto(out *KickRequestSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickRequestSpec.
func (in *KickRequestSpec) DeepCopy() *KickRequestSpec {
	if in == nil {
		return nil
	}
	out := new(KickRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KickRequestStatus) DeepCopyInto(out *KickRequestStatus) {
	*out = *in
	out.Owner = in.Owner
	in.Gate.DeepCopyInto(&out.Gate)
	if in.LatestObservedDependencyChange != nil {
		in, out := &in.LatestObservedDependencyChange, &out.LatestObservedDependencyChange
		*out = (*in).DeepCopy()
	}
	in.CurrentRollout.DeepCopyInto(&out.CurrentRollout)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KickRequestStatus.
func (in *KickRequestStatus) DeepCopy() *KickRequestStatus {
	if in == nil {
		return nil
	}
	out := new(KickRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}
