//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *KickRequest) DeepCopyInto(out *KickRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KickRequest) DeepCopy() *KickRequest {
	if in == nil {
		return nil
	}
	out := new(KickRequest)
	in.DeepCopyInto(out)
	return out
}

func (in *KickRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KickRequestList) DeepCopyInto(out *KickRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KickRequest, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KickRequestList) DeepCopy() *KickRequestList {
	if in == nil {
		return nil
	}
	out := new(KickRequestList)
	in.DeepCopyInto(out)
	return out
}

func (in *KickRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KickRequestStatus) DeepCopyInto(out *KickRequestStatus) {
	*out = *in
	if in.Gate.RequeueAt != nil {
		out.Gate.RequeueAt = in.Gate.RequeueAt.DeepCopy()
	}
	if in.LatestObservedDependencyChange != nil {
		out.LatestObservedDependencyChange = in.LatestObservedDependencyChange.DeepCopy()
	}
	if in.CurrentRollout.StartedAt != nil {
		out.CurrentRollout.StartedAt = in.CurrentRollout.StartedAt.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}
