{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kick-manager-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kick.corewire.io"]
    resources: ["kickrequests"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["kick.corewire.io"]
    resources: ["kickrequests/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["kick.corewire.io"]
    resources: ["kickpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kick.corewire.io"]
    resources: ["kickpolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["kick.corewire.io"]
    resources: ["notificationpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kick.corewire.io"]
    resources: ["notificationpolicies/status"]
    verbs: ["get", "update", "patch"]
{{- if .Values.integrations.argocd.enabled }}
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if .Values.integrations.flux.enabled }}
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if .Values.integrations.argoRollouts.enabled }}
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list", "watch", "patch"]
{{- end }}
{{- if .Values.integrations.secretsStoreCSI.enabled }}
  - apiGroups: ["secrets-store.csi.x-k8s.io"]
    resources: ["secretproviderclasses", "secretproviderclasspodstatuses"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if .Values.integrations.kargo.enabled }}
  - apiGroups: ["kargo.akuity.io"]
    resources: ["stages", "promotions"]
    verbs: ["get", "list", "watch"]
{{- end }}
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
{{- end }}
