{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kick-controller-manager
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kick
      app.kubernetes.io/component: controller-manager
{{- end }}
